### ISSUE TITLE
There are issues regarding the code.

### ISSUE THREAD

**Issue by yejian95** [sssleverlily/ISMnet#1]
Hello, author! Could you please provide the complete runnable code? I am new to this area and would really appreciate your help.

**Comment by sssleverlily** [comment]
> Hello, author! Could you please provide the complete runnable code? I am new to this area and would really appreciate your help.

Thank you for your attention, we will revise it soon!

**Comment by sssleverlily** [comment]
> Hello, author! Could you please provide the complete runnable code? I am new to this area and would really appreciate your help.

hi! I have uploaded data generate code —— dataProcess.py, you should first run dataProcess.py to generate data, if you have other questions, please ask me！
