### ISSUE TITLE
How do you use SIR to get the true influence labels of nodes or simplexes?

### ISSUE THREAD

**Issue by I1ikestudy** [sssleverlily/ISMnet#2]
After reading your paper and code, I realized that you are reading the data from the CSV file through the get_SIR function and performing the mean value calculation on this data to generate the true influence labels. But when running the file train_model_gridSearch.py, it reports error FileNotFoundError: [Errno 2] No such file or directory: '... \\data\\hep\\2-simplex\\HL_hep.pt'. So could you please tell me exactly how I can use SIR to get the true influence label of a node or simplex?

**Comment by I1ikestudy** [comment]
I am new to this field and would appreciate any advice you can give!

**Comment by sssleverlily** [comment]
> After reading your paper and code, I realized that you are reading the data from the CSV file through the get_SIR function and performing the mean value calculation on this data to generate the true influence labels. But when running the file train_model_gridSearch.py, it reports error FileNotFoundError: [Errno 2] No such file or directory: '... \data\hep\2-simplex\HL_hep.pt'. So could you please tell me exactly how I can use SIR to get the true influence label of a node or simplex?

hi! I have uploaded data generate code —— dataProcess.py, you should first run dataProcess.py to generate data, if you have other questions, please ask me！

**Comment by yejian95** [comment]
> > 在阅读了您的论文和代码后，我意识到您正在通过 get_SIR 函数从 CSV 文件中读取数据，并对此数据执行平均值计算以生成真正的影响标签。但是，当train_model_gridSearch.py运行文件时，它会报告错误 FileNotFoundError： [Errno 2] No such file or directory： '... \data\hep\2-simplex\HL_hep.pt'。那么，您能否告诉我如何使用 SIR 来获取节点或单纯形的真实影响标签？
> 
> 你好！我已经上传了数据生成代码 —— dataProcess.py，你应该先运行 dataProcess.py 来生成数据，如果你还有其他问题，请问我！

你好，以Hep数据为例子，我运行完dataProcess.py，再执行train_model_gridSearch.py，也显示FileNotFoundError: [Errno 2] No such file or directory: '../data/hep/2-simplex/HL_hep.pt。然后，我在以下路径没有找到相关文件/data/hep/2-simplex/  。请问一下，应该是哪里出现问题了呢，导致运行完dataProcess.py没有生成数据？
