### ISSUE TITLE
运行dataProcess.py后没有生成相关文件？

### ISSUE THREAD

**Issue by yejian95** [sssleverlily/ISMnet#4]
你好，以Hep数据为例子，我运行完dataProcess.py，再执行train_model_gridSearch.py，也显示FileNotFoundError: [Errno 2] No such file or directory: '../data/hep/2-simplex/HL_hep.pt。然后，我在以下路径没有找到相关文件/data/hep/2-simplex/ 。请问一下，应该是哪里出现问题了呢，导致运行完dataProcess.py没有生成数据？

**Comment by I1ikestudy** [comment]
dataProcess.py文件中处理的数据集是figeys，而因为train_model_gridSearch.py中指定的数据集是默认数据集hep，需要将其更改为figeys后代码才能跑起来
